// Generated by Wrangler on Thu Sep 05 2024 14:34:10 GMT+0100 (British Summer Time)
// by running `wrangler types`

interface Env {
	CLOUDFLARE_API_KEY: string;
	CLOUDFLARE_ACCOUNT_ID: string;
	LLM: Ai;
}
